//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvalonDock.WinFormsTestApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n        <?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n        <LayoutRoot xmlns:xsi=\"" +
            "http://www.w3.org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XML" +
            "Schema\">\r\n        <RootPanel Orientation=\"Horizontal\">\r\n        <LayoutDocumentP" +
            "aneGroup Orientation=\"Horizontal\">\r\n        <LayoutDocumentPane>\r\n        <Layou" +
            "tDocument Title=\"Document 1\" IsSelected=\"True\" ContentId=\"document1\" FloatingLef" +
            "t=\"167\" FloatingTop=\"237\" FloatingWidth=\"327\" FloatingHeight=\"291\" LastActivatio" +
            "nTimeStamp=\"09/03/2012 15:42:16\" />\r\n        </LayoutDocumentPane>\r\n        <Lay" +
            "outDocumentPane>\r\n        <LayoutDocument Title=\"Document 2\" IsSelected=\"True\" I" +
            "sLastFocusedDocument=\"True\" ContentId=\"document2\" FloatingLeft=\"265\" FloatingTop" +
            "=\"250\" FloatingWidth=\"161\" FloatingHeight=\"291\" LastActivationTimeStamp=\"09/03/2" +
            "012 15:42:16\" />\r\n        </LayoutDocumentPane>\r\n        </LayoutDocumentPaneGro" +
            "up>\r\n        <LayoutAnchorablePaneGroup Orientation=\"Vertical\" DockWidth=\"120\">\r" +
            "\n        <LayoutAnchorablePane DockWidth=\"120\" FloatingWidth=\"132\" FloatingHeigh" +
            "t=\"291\" FloatingLeft=\"455\" FloatingTop=\"248\">\r\n        <LayoutAnchorable CanHide" +
            "=\"False\" AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"WinForms Window\" " +
            "IsSelected=\"True\" ContentId=\"toolWindow3\" FloatingLeft=\"455\" FloatingTop=\"248\" F" +
            "loatingWidth=\"132\" FloatingHeight=\"291\" CanClose=\"False\" LastActivationTimeStamp" +
            "=\"09/03/2012 15:41:54\" />\r\n        </LayoutAnchorablePane>\r\n        <LayoutAncho" +
            "rablePaneGroup Orientation=\"Horizontal\" FloatingWidth=\"150\" FloatingHeight=\"143\"" +
            " FloatingLeft=\"433\" FloatingTop=\"280\">\r\n        <LayoutAnchorablePane FloatingWi" +
            "dth=\"150\" FloatingHeight=\"143\" FloatingLeft=\"433\" FloatingTop=\"280\">\r\n        <L" +
            "ayoutAnchorable AutoHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Tool Windo" +
            "w 2\" IsSelected=\"True\" ContentId=\"toolWindow2\" FloatingLeft=\"433\" FloatingTop=\"2" +
            "80\" FloatingWidth=\"150\" FloatingHeight=\"143\" LastActivationTimeStamp=\"09/03/2012" +
            " 15:41:56\" />\r\n        </LayoutAnchorablePane>\r\n        </LayoutAnchorablePaneGr" +
            "oup>\r\n        </LayoutAnchorablePaneGroup>\r\n        <LayoutAnchorablePane Id=\"56" +
            "84e345-b25d-434f-912d-2392e7762d97\" DockWidth=\"138\" FloatingWidth=\"150\" Floating" +
            "Height=\"143\" FloatingLeft=\"472\" FloatingTop=\"243\">\r\n        <LayoutAnchorable Au" +
            "toHideMinWidth=\"100\" AutoHideMinHeight=\"100\" Title=\"Tool Window 1\" IsSelected=\"T" +
            "rue\" ContentId=\"toolWindow1\" FloatingLeft=\"472\" FloatingTop=\"243\" FloatingWidth=" +
            "\"150\" FloatingHeight=\"143\" LastActivationTimeStamp=\"09/03/2012 15:41:57\" />\r\n   " +
            "     </LayoutAnchorablePane>\r\n        </RootPanel>\r\n        <TopSide />\r\n       " +
            " <RightSide />\r\n        <LeftSide>\r\n        <LayoutAnchorGroup>\r\n        <Layout" +
            "Anchorable AutoHideMinWidth=\"300\" AutoHideMinHeight=\"100\" Title=\"AutoHide1 Conte" +
            "nt\" ContentId=\"AutoHide1Content\" />\r\n        <LayoutAnchorable AutoHideMinWidth=" +
            "\"100\" AutoHideMinHeight=\"100\" Title=\"AutoHide2 Content\" ContentId=\"AutoHide2Cont" +
            "ent\" />\r\n        </LayoutAnchorGroup>\r\n        </LeftSide>\r\n        <BottomSide " +
            "/>\r\n        <FloatingWindows />\r\n        <Hidden />\r\n        </LayoutRoot>\r\n    " +
            "  ")]
        public string DefaultLayout {
            get {
                return ((string)(this["DefaultLayout"]));
            }
            set {
                this["DefaultLayout"] = value;
            }
        }
    }
}
